export enum ServiceCode {
  PAJAK = "PAJAK",
  PLN = "PLN",
  PDAM = "PDAM",
  PULSA = "PULSA",
  PGN = "PGN",
  MUSIK = "MUSIK",
  TV = "TV",
  PAKET_DATA = "PAKET_DATA",
  VOUCHER_GAME = "VOUCHER_GAME",
  VOUCHER_MAKANAN = "VOUCHER_MAKANAN",
  QURBAN = "QURBAN",
  ZAKAT = "ZAKAT",
}


